SalesWebMvc/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SalesWebMvc.Data;
using SalesWebMvc.Models;

namespace SalesWebMvc.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly SalesWebMvcContext _context;

        public DepartmentsController(SalesWebMvcContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Department.ToListAsync());
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Department.FindAsync(id);
            _context.Department.Remove(department);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Department.Any(e => e.Id == id);
        }
    }
}

SalesWebMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SalesWebMvc.Models.ViewModels;

namespace SalesWebMvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Salles Web MVC App from C# Course";
            ViewData["Email"] = "magaldev7@gmail.com";
            ViewData["Developer"] = "Marcelo Magalhães";

            return View(); // return view é um método de builder
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "My contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SalesWebMvc/Controllers/SalesRecordsController.cs
using Microsoft.AspNetCore.Mvc;
using SalesWebMvc.Services;
using System;
using System.Threading.Tasks;

namespace SalesWebMvc.Controllers
{
    public class SalesRecordsController : Controller
    {

        private readonly SalesRecordService _salesRecordService;

        public SalesRecordsController(SalesRecordService salesRecordService)
        {
            _salesRecordService = salesRecordService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> SimpleSearch(DateTime? minDate, DateTime? maxDate)
        {
            // Padronizando como o formulário deve iniciar 
            if (!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year, 1, 1);
            }
            if (!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }
            ViewData["minDate"] = minDate.Value.ToString("yyyy-MM-dd");
            ViewData["maxDate"] = maxDate.Value.ToString("yyyy-MM-dd");


            var result = await _salesRecordService.FindByDateAsync(minDate, maxDate);

            return View(result);
        }
        public async Task<IActionResult> GroupingSearch(DateTime? minDate, DateTime? maxDate)
        {
            // Padronizando como o formulário deve iniciar 
            if (!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year, 1, 1);
            }
            if (!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }
            ViewData["minDate"] = minDate.Value.ToString("yyyy-MM-dd");
            ViewData["maxDate"] = maxDate.Value.ToString("yyyy-MM-dd");
            var result = await _salesRecordService.FindByDateGroupingAsync(minDate, maxDate);
            return View(result);
        }
    }
}

SalesWebMvc/Controllers/SellersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SalesWebMvc.Models;
using SalesWebMvc.Models.ViewModels;
using SalesWebMvc.Services;
using SalesWebMvc.Services.Exceptions;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace SalesWebMvc.Controllers
{
    public class SellersController : Controller // este controlador recebeu a chamada do caminho /sellers
    {
        private readonly SellerService _sellerService; // declarando dependência para este serviço
        private readonly DepartmentService _departmentService;

        public SellersController(SellerService sellerService, DepartmentService departmentService) // setando a controller para receber nosso serviço
        {
            _sellerService = sellerService;
            _departmentService = departmentService;
        }
        public async Task<IActionResult> Index()
        {
            var list = await _sellerService.FindAllAsync(); // esta operação vai retornar uma lista de seller

            return View(list); // passando a lista como argumento pra gerar um IActionResult contendo essa lista. (MVC)

            // chamamos o controlador, o controlador acessou nosso model, pegou o dado da lista e vai encaminhar para nossa VIEW!
        }
        public async Task<IActionResult> Create()
        {
            var departments = await _departmentService.FindAllAsync(); // buscar os deps
            var viewModel = new SellerFormViewModel { Departments = departments };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] // evita que conteúdos maliciosos sejam enviados pelo nosso Http
        public async Task<IActionResult> Create(Seller seller) // n precisa acrescentar o dpt id pois o framework já faz a intermediação
        {  /* o if abaixo, representa navegadores ou ocasiões onde o JS tá desabilitado na WEB, e a requisição não é instanciada
              desta forma, o if valida que se não chegar nenhuma requisição por conta do JS desabilitado ou afins, é pra BARRAR a edição! */
            if (!ModelState.IsValid)
            {           
                var departments = await _departmentService.FindAllAsync(); // Obtém todos os departamentos através do serviço _departmentService
                var viewModel = new SellerFormViewModel // Cria uma instância do ViewModel SellerFormViewModel com os dados do vendedor e a lista de departamentos
                {
                    Seller = seller, // Define o vendedor no ViewModel
                    Departments = departments // Define a lista de departamentos no ViewModel
                };
                // Retorna a visão (View) com o ViewModel criado
                return View(viewModel);
            }
               await _sellerService.InsertAsync(seller); // método de inserir, agregado ao nosso serviço 
            return RedirectToAction(nameof(Index)); // redireciona nossa inserção para o Index, nameof é para que caso eu mude o nome do Index eu não precise alterar mais nada
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id not provided"});
            }

            var obj = await _sellerService.FindByIdAsync(id.Value); // tem q passar como value pois ele é um obj opcional
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id not found" });
            }

            return View(obj); // caso passe pelos if, entra na nossa View(obj) 
        }
        // Método do delete acrescentado!
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {           // tratando exceções
            try
            {
                await _sellerService.RemoveAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (IntegrityException e)
            {
                return RedirectToAction(nameof(Error), new {message = e.Message});
            }
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id  not provided" });
            }
            var obj = await _sellerService.FindByIdAsync(id.Value);
            if (obj == null)
            {

                return RedirectToAction(nameof(Error), new { message = "Id  not found" });
            }
            return View(obj);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id  not provided" });
            }

            var obj = await _sellerService.FindByIdAsync(id.Value);
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id  not found" });
            }

            List<Department> departments = await _departmentService.FindAllAsync();
            SellerFormViewModel viewModel = new SellerFormViewModel { Seller = obj, Departments = departments };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Seller seller)
        {
            /* o if abaixo, representa navegadores ou ocasiões onde o JS tá desabilitado na WEB, e a requisição não é instanciada
              desta forma, o if valida que se não chegar nenhuma requisição por conta do JS desabilitado ou afins, é pra BARRAR a edição! */
            if (!ModelState.IsValid)
            {
                var departments = await _departmentService.FindAllAsync(); // Obtém todos os departamentos através do serviço _departmentService
                var viewModel = new SellerFormViewModel // Cria uma instância do ViewModel SellerFormViewModel com os dados do vendedor e a lista de departamentos
                {
                    Seller = seller, // Define o vendedor no ViewModel
                    Departments = departments // Define a lista de departamentos no ViewModel
                };
            }
                if (id != seller.Id)
            {
                return RedirectToAction(nameof(Error), new { message = "Id mismatch" });
            }
            try
            {
                await _sellerService.UpdateAsync(seller);
                return RedirectToAction(nameof(Index));
            }

           /* Podemos utilizar o appexception genérico, pois ele busca o upcasting do dbconcrr...
             catch (ApplicationException e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            } */ 

            catch (NotFoundException e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }
            catch (DbConcurrencyException e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }
        }

        public IActionResult Error(string message)
        {
            // Cria uma instância de ErrorViewModel com a mensagem de erro fornecida e o ID da requisição atual
            var viewModel = new ErrorViewModel
            {
                Message = message, // Define a mensagem de erro recebida como argumento
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier // Obtém o ID da atividade atual ou do identificador de rastreamento do HTTP
            }; // Activity faz parte do using System.Diagnostics

            // Retorna a visão de erro junto com o ViewModel
            return View(viewModel);
        }
    }
}

SalesWebMvc/Views/Home/About.cshtml
@{ // <-- bloco q permite usar html e c# 
   
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>


<p>Developer: @ViewData["Developer"]</p>
<p>@ViewData["Email"]</p>

<address>
    <strong>Rede Social: </strong> <a href="https://www.linkedin.com/in/marcelo-magalhães-513b6b283" target="_blank">LinkedIn</a>
</address>

SalesWebMvc/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>My contact page: </h3>

<address>
    <strong>Rede Social: </strong> <a href="https://www.linkedin.com/in/marcelo-magalhães-513b6b283" target="_blank">LinkedIn</a><br />
    <strong>Whatsapp: </strong> <a href="https://wa.me/5511948683746" target="_blank">Contato Comecial</a>
</address>

SalesWebMvc/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/estilo.css">
    <title>Projeto de Apresentação Currícular</title>
</head>

<body>
    <br />
    <style>
        .cabecalho {
            text-align: center;
        }

    </style>

    <div class="cabecalho">
        <a href="https://github.com/magal07" target="_blank" class="logo-csharp">
        </a>
        </svg>
        </span>
        <div class="cabecalho-conteudo">
            <h1><a href="https://github.com/magal07/Projeto-ASP-NET-CORE-WEB">PROJETO ASP NET CORE MVC</a></h1>
            <h2>
                <a href="https://github.com/magal07">GitHub, </a>
                <a href="https://www.linkedin.com/in/marcelo-magalhães-513b6b283/">LinkedIn</a>
            </h2>
            <h2>Desenvolvido por Marcelo Magalhães.</h2>

		</div>
	</div>
    </header>
    <main class="principal">
        <div class="conteudo">
            <nav class="modulos">
                <div class="modulo azul">
                    <h3>Departments</h3>
                    <ul>
                        <li>
                            <a href="@Url.Action("Index", "Departments")">
                                View Departments
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create", "Departments")">
                                Creat New Department
                            </a>
                        </li>
                    </ul>
                </div>                
                <div class="modulo azul">
                    <h3>Sellers</h3>
                    <ul>
                        <li>
                            <a href="@Url.Action("Create", "Sellers")">
                                View Sellers
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create", "Sellers")">
                                Creat New
                            </a>
                        </li>
                    </ul>
                </div>
                                <div class="modulo azul">
                    <h3>Sales</h3>
                    <ul>
                        <li>
                            <a href="@Url.Action("Index", "SalesRecords")">
                                Simple Search
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("GroupingSearch", "SalesRecords")">
                                Grouping Search
							</a>
                        </li>
                    </ul>
                </div>
                                                <div class="modulo azul">
                    <h3>About</h3>
                    <ul>
                        <li>
                            <a href="@Url.Action("About", "Home")">
                                Get to know me
                            </a>
                        </li>
                    </ul>
                </div>
                                                <div class="modulo azul">
                    <h3>Contact</h3>
                    <ul>
                        <li>
                            <a href="@Url.Action("Contact", "Home")">
                                Contact me
                            </a>
                        </li>
                    </ul>
                </div>
                </div>
    </main>
    <footer class="rodape">
        SIGA-NOS NAS REDES SOCIAIS:
        <a href="https://github.com/magal07" target="_blank"><img src="~/images/git-icon.png" alt="GitHub"></a>
        <a href="https://www.linkedin.com/in/marcelo-magalhães-513b6b283" target="_blank"><img src="~/images/linkedin-icon.png" alt="LinkedIn"></a>
        <a href="https://wa.me/5511948683746" target="_blank"><img src="~/images/whatsapp-icon.png" alt="Whatsapp"></a>       
    </footer>

</body>
</html>